# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='customer',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='product',
            field=models.CharField(max_length=255),
        ),
    ]
